# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    endpoints.py                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jre-gonz <jre-gonz@student.42madrid.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/30 12:50:45 by jre-gonz          #+#    #+#              #
#    Updated: 2022/08/30 12:54:06 by jre-gonz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

API42ENPOINTS = {
	"Accreditations": {
		"/v2/accreditations",
		"/v2/accreditations/:id",
	},
	"Achievements": {
		"/v2/achievements",
		"/v2/cursus/:cursus_id/achievements",
		"/v2/campus/:campus_id/achievements",
		"/v2/titles/:title_id/achievements",
		"/v2/achievements/:id",
	},
	"Achievements users": {
		"/v2/achievements/:achievement_id/achievements_users",
		"/v2/achievements_users",
		"/v2/achievements_users/:id",
	},
	"Amendments": {
		"/v2/amendments",
		"/v2/users/:user_id/amendments",
		"/v2/internships/:internship_id/amendments",
		"/v2/amendments/:id",
	},
	"Announcements": {
		"/v2/announcements/graph(/on/:field(/by/:interval))",
		"/v2/announcements/:id",
		"/v2/announcements",
		"/v2/cursus/:cursus_id/announcements",
	},
	"Anti grav units": {
		"/v2/anti_grav_units",
		"/v2/anti_grav_units/:id",
	},
	"Anti grav units users": {
		"/v2/anti_grav_units_users",
		"/v2/users/:user_id/anti_grav_units_users",
		"/v2/campus/:campus_id/anti_grav_units_users",
		"/v2/anti_grav_units_users/:id",
	},
	"Apps": {
		"/v2/apps",
		"/v2/users/:user_id/apps",
		"/v2/apps/:id",
	},
	"Attachments": {
		"/v2/project_sessions/:project_session_id/attachments",
		"/v2/projects/:project_id/attachments",
		"/v2/attachments",
		"/v2/project_sessions/:project_session_id/attachments/:id",
		"/v2/attachments/:id",
	},
	"Balances": {
		"/v2/balances",
		"/v2/pools/:pool_id/balances",
		"/v2/balances/:id",
		"/v2/pools/:pool_id/balances/:id",
	},
	"Bloc deadlines": {
		"/v2/bloc_deadlines",
		"/v2/blocs/:bloc_id/bloc_deadlines",
		"/v2/bloc_deadlines/:id",
	},
	"Blocs": {
		"/v2/blocs",
		"/v2/blocs/:id",
	},
	"Broadcasts": {
		"/v2/campus/:campus_id/broadcasts",
	},
	"Campus": {
		"/v2/campus",
		"/v2/campus/:id",
		"/v2/campus/:campus_id/stats",
	},
	"Campus users": {
		"/v2/campus_users",
		"/v2/users/:user_id/campus_users",
		"/v2/campus_users/:id",
	},
	"Certificates": {
		"/v2/certificates",
		"/v2/certificates/:id",
	},
	"Certificates users": {
		"/v2/certificates_users",
		"/v2/certificates/:certificate_id/certificates_users",
		"/v2/users/:user_id/certificates_users",
		"/v2/certificates_users/:id",
	},
	"Closes": {
		"/v2/closes",
		"/v2/users/:user_id/closes",
		"/v2/closes/:id",
		"/v2/closes/:id/unclose",
		"/v2/closes/:id/close",
	},
	"Coalitions": {
		"/v2/coalitions",
		"/v2/users/:user_id/coalitions",
		"/v2/blocs/:bloc_id/coalitions",
		"/v2/coalitions/:id",
	},
	"Coalitions users": {
		"/v2/coalitions/:coalition_id/coalitions_users",
		"/v2/coalitions_users",
		"/v2/users/:user_id/coalitions_users",
		"/v2/coalitions_users/:id",
	},
	"Commands": {
		"/v2/products/:product_id/commands",
		"/v2/campus/:campus_id/products/:product_id/commands",
	},
	"Community services": {
		"/v2/community_services/graph(/on/:field(/by/:interval))",
		"/v2/closes/:close_id/community_services",
		"/v2/community_services",
		"/v2/community_services/:id",
		"/v2/community_services/:id/validate",
		"/v2/community_services/:id/invalidate",
	},
	"Companies": {
		"/v2/companies",
		"/v2/companies/:id",
		"/v2/companies/:company_id/subscribed_users",
		"/v2/companies/:company_id/internships_users",
	},
	"Correction point historics": {
		"/v2/users/:user_id/correction_point_historics",
	},
	"Cursus": {
		"/v2/cursus",
		"/v2/cursus/:id",
	},
	"Cursus users": {
		"/v2/cursus_users/graph(/on/:field(/by/:interval))",
		"/v2/cursus_users",
		"/v2/users/:user_id/cursus_users",
		"/v2/cursus/:cursus_id/cursus_users",
		"/v2/cursus_users/:id",
	},
	"Dashes": {
		"/v2/dashes/graph(/on/:field(/by/:interval))",
		"/v2/dashes",
		"/v2/dashes/:id",
	},
	"Dashes users": {
		"/v2/dashes_users/graph(/on/:field(/by/:interval))",
		"/v2/dashes_users",
		"/v2/dashes/:dash_id/dashes_users",
		"/v2/dashes_users/:id",
	},
	"Endpoints": {
		"/v2/endpoints",
		"/v2/endpoints/:id",
	},
	"Evaluations": {
		"/v2/evaluations",
		"/v2/evaluations/:id",
	},
	"Events": {
		"/v2/events/graph(/on/:field(/by/:interval))",
		"/v2/cursus/:cursus_id/events",
		"/v2/campus/:campus_id/events",
		"/v2/campus/:campus_id/cursus/:cursus_id/events",
		"/v2/users/:user_id/events",
		"/v2/events",
		"/v2/events/:id",
	},
	"Events users": {
		"/v2/users/:user_id/events_users",
		"/v2/events/:event_id/events_users",
		"/v2/events_users",
		"/v2/events_users/:id",
	},
	"Exams": {
		"/v2/exams/graph(/on/:field(/by/:interval))",
		"/v2/cursus/:cursus_id/exams",
		"/v2/campus/:campus_id/exams",
		"/v2/campus/:campus_id/cursus/:cursus_id/exams",
		"/v2/users/:user_id/exams",
		"/v2/projects/:project_id/exams",
		"/v2/exams",
		"/v2/exams/:id",
	},
	"Exams users": {
		"/v2/exams/:exam_id/exams_users",
		"/v2/exams/:exam_id/exams_users/:id",
	},
	"Experiences": {
		"/v2/experiences",
		"/v2/campus/:campus_id/experiences",
		"/v2/projects_users/:projects_user_id/experiences",
		"/v2/users/:user_id/experiences",
		"/v2/skills/:skill_id/experiences",
		"/v2/partnerships_users/:partnerships_user_id/experiences",
		"/v2/experiences/:id",
	},
	"Expertises": {
		"/v2/expertises",
		"/v2/expertises/:id",
	},
	"Expertises users": {
		"/v2/expertises/:expertise_id/expertises_users",
		"/v2/users/:user_id/expertises_users",
		"/v2/expertises_users",
		"/v2/expertises_users/:id",
	},
	"Feedbacks": {
		"/v2/events/:event_id/feedbacks",
		"/v2/feedbacks",
		"/v2/scale_teams/:scale_team_id/feedbacks",
	},
	"Flags": {
		"/v2/flags",
	},
	"Flash users": {
		"/v2/flashes/:flash_id/flash_users",
		"/v2/flash_users",
		"/v2/flashes/:flash_id/flash_users/:id",
		"/v2/flash_users/:id",
	},
	"Flashes": {
		"/v2/flashes",
		"/v2/flashes/:id",
	},
	"Gitlab users": {
		"/v2/users/:user_id/gitlab_users",
	},
	"Groups": {
		"/v2/groups",
		"/v2/users/:user_id/groups",
		"/v2/groups/:id",
	},
	"Groups users": {
		"/v2/groups_users",
		"/v2/groups/:group_id/groups_users",
		"/v2/users/:user_id/groups_users",
		"/v2/groups_users/:id",
	},
	"Internships": {
		"/v2/internships",
		"/v2/users/:user_id/internships",
		"/v2/internships/:id",
	},
	"Journals": {
		"/v2/campus/:campus_id/journals",
	},
	"Languages": {
		"/v2/languages/graph(/on/:field(/by/:interval))",
		"/v2/languages",
		"/v2/languages/:id",
	},
	"Languages users": {
		"/v2/languages_users/graph(/on/:field(/by/:interval))",
		"/v2/users/:user_id/languages_users",
		"/v2/languages_users",
		"/v2/users/:user_id/languages_users/:id",
		"/v2/languages_users/:id",
	},
	"Levels": {
		"/v2/levels",
		"/v2/cursus/:cursus_id/levels",
	},
	"Locations": {
		"/v2/locations/graph(/on/:field(/by/:interval))",
		"/v2/locations",
		"/v2/users/:user_id/locations",
		"/v2/campus/:campus_id/locations",
		"/v2/locations/:id",
		"/v2/users/:user_id/locations/:id",
		"/v2/campus/:campus_id/locations/end_all",
	},
	"Mailings": {
		"/v2/mailings",
		"/v2/users/:user_id/mailings",
		"/v2/mailings/:id",
	},
	"Notes": {
		"/v2/users/:user_id/notes",
		"/v2/campus/:campus_id/notes",
		"/v2/notes",
		"/v2/notes/:id",
	},
	"Notions": {
		"/v2/cursus/:cursus_id/notions",
		"/v2/tags/:tag_id/notions",
		"/v2/notions",
		"/v2/notions/:id",
	},
	"Offers": {
		"/v2/offers",
		"/v2/offers/:id",
	},
	"Offers users": {
		"/v2/offers/:offer_id/offers_users",
		"/v2/users/:user_id/offers_users",
		"/v2/offers_users",
		"/v2/offers_users/:id",
	},
	"Params project sessions rules": {
		"/v2/project_sessions_rules/:project_sessions_rule_id/params_project_sessions_rules",
		"/v2/params_project_sessions_rules",
		"/v2/params_project_sessions_rules/:id",
	},
	"Partnerships": {
		"/v2/partnerships",
		"/v2/partnerships/:id",
	},
	"Partnerships users": {
		"/v2/partnerships/:partnership_id/partnerships_users",
		"/v2/partnerships_users",
		"/v2/partnerships_users/:id",
	},
	"Patronages": {
		"/v2/patronages",
		"/v2/users/:user_id/patronages",
		"/v2/patronages/:id",
	},
	"Patronages reports": {
		"/v2/patronages_reports/graph(/on/:field(/by/:interval))",
		"/v2/patronages_reports",
		"/v2/users/:user_id/patronages_reports",
		"/v2/patronages/:patronage_id/patronages_reports",
		"/v2/reports/:report_id/patronages_reports",
		"/v2/patronages_reports/:id",
	},
	"Pools": {
		"/v2/pools",
		"/v2/pools/:id",
		"/v2/pools/:id/points/add",
		"/v2/pools/:id/points/remove",
	},
	"Products": {
		"/v2/products",
		"/v2/campus/:campus_id/products",
		"/v2/products/:id",
		"/v2/campus/:campus_id/products/:id",
	},
	"Project data": {
		"/v2/project_data",
		"/v2/project_sessions/:project_session_id/project_data",
		"/v2/project_data/:id",
	},
	"Project sessions": {
		"/v2/projects/:project_id/project_sessions/graph(/on/:field(/by/:interval))",
		"/v2/project_sessions/graph(/on/:field(/by/:interval))",
		"/v2/projects/:project_id/project_sessions",
		"/v2/project_sessions",
		"/v2/project_sessions/:id",
	},
	"Project sessions rules": {
		"/v2/project_sessions/:project_session_id/project_sessions_rules",
		"/v2/project_sessions_rules",
		"/v2/project_sessions_rules/:id",
	},
	"Project sessions skills": {
		"/v2/project_sessions_skills",
		"/v2/project_sessions/:project_session_id/project_sessions_skills",
		"/v2/skills/:skill_id/project_sessions_skills",
		"/v2/project_sessions_skills/:id",
		"/v2/project_sessions/:project_session_id/project_sessions_skills/:id",
	},
	"Projects": {
		"/v2/cursus/:cursus_id/projects",
		"/v2/projects/:project_id/projects",
		"/v2/projects",
		"/v2/me/projects",
		"/v2/projects/:id",
		"/v2/projects/:id/retry",
	},
	"Projects users": {
		"/v2/projects/:project_id/projects_users/graph(/on/:field(/by/:interval))",
		"/v2/users/:user_id/projects_users/graph(/on/:field(/by/:interval))",
		"/v2/projects_users/graph(/on/:field(/by/:interval))",
		"/v2/projects/:project_id/projects_users",
		"/v2/users/:user_id/projects_users",
		"/v2/projects_users",
		"/v2/projects_users/:id",
		"/v2/projects/:project_id/register",
		"/v2/projects_users/:id/compile",
		"/v2/projects_users/:id/retry",
	},
	"Quests": {
		"/v2/quests",
		"/v2/cursus/:cursus_id/quests",
		"/v2/campus/:campus_id/quests",
		"/v2/users/:user_id/quests",
		"/v2/quests/:id",
	},
	"Quests users": {
		"/v2/quests_users/graph(/on/:field(/by/:interval))",
		"/v2/quests/:quest_id/quests_users",
		"/v2/users/:user_id/quests_users",
		"/v2/quests_users",
		"/v2/quests_users/:id",
	},
	"Roles": {
		"/v2/roles",
		"/v2/users/:user_id/roles",
		"/v2/roles/:id",
	},
	"Roles entities": {
		"/v2/roles_entities/graph(/on/:field(/by/:interval))",
		"/v2/roles/:role_id/roles_entities",
		"/v2/roles_entities",
		"/v2/roles_entities/:id",
	},
	"Rules": {
		"/v2/rules",
		"/v2/project_sessions/:project_session_id/rules",
		"/v2/rules/:id",
	},
	"Scale teams": {
		"/v2/scale_teams/graph(/on/:field(/by/:interval))",
		"/v2/projects/:project_id/scale_teams/graph(/on/:field(/by/:interval))",
		"/v2/users/:user_id/scale_teams/graph(/on/:field(/by/:interval))",
		"/v2/project_sessions/:project_session_id/scale_teams",
		"/v2/scale_teams",
		"/v2/projects/:project_id/scale_teams",
		"/v2/users/:user_id/scale_teams/as_corrector",
		"/v2/users/:user_id/scale_teams/as_corrected",
		"/v2/users/:user_id/scale_teams",
		"/v2/me/scale_teams/as_corrector",
		"/v2/me/scale_teams/as_corrected",
		"/v2/me/scale_teams",
		"/v2/project_sessions/:project_session_id/scale_teams/:id",
		"/v2/scale_teams/:id",
		"/v2/scale_teams/multiple_create",
	},
	"Scales": {
		"/v2/project_sessions/:project_session_id/scales",
		"/v2/scales",
		"/v2/projects/:project_id/scales",
		"/v2/users/:user_id/scales",
		"/v2/scales/:id",
	},
	"Scores": {
		"/v2/scores",
		"/v2/coalitions/:coalition_id/scores",
		"/v2/coalitions_users/:coalitions_user_id/scores",
		"/v2/blocs/:bloc_id/scores",
		"/v2/blocs/:bloc_id/scores/:id",
		"/v2/coalitions/:coalition_id/scores/:id",
	},
	"Skills": {
		"/v2/skills",
		"/v2/cursus/:cursus_id/skills",
		"/v2/skills/:id",
	},
	"Slots": {
		"/v2/slots/graph(/on/:field(/by/:interval))",
		"/v2/projects/:project_id/slots/graph(/on/:field(/by/:interval))",
		"/v2/users/:user_id/slots/graph(/on/:field(/by/:interval))",
		"/v2/slots",
		"/v2/projects/:project_id/slots",
		"/v2/users/:user_id/slots",
		"/v2/me/slots",
		"/v2/slots/:id",
	},
	"Squads": {
		"/v2/blocs/:bloc_id/squads",
		"/v2/blocs/:bloc_id/squads/:id",
		"/v2/squads/:id",
	},
	"Squads users": {
		"/v2/blocs/:bloc_id/squads_users",
		"/v2/blocs/:bloc_id/squads_users/:id",
		"/v2/squads_users/:id",
	},
	"Subnotions": {
		"/v2/notions/:notion_id/subnotions",
		"/v2/subnotions",
		"/v2/subnotions/:id",
	},
	"Tags": {
		"/v2/projects/:project_id/tags",
		"/v2/issues/:issue_id/tags",
		"/v2/notions/:notion_id/tags",
		"/v2/cursus/:cursus_id/tags",
		"/v2/users/:user_id/tags",
		"/v2/tags",
		"/v2/tags/:id",
	},
	"Tags users": {
		"/v2/tags_users",
		"/v2/users/:user_id/tags_users",
		"/v2/cursus/:cursus_id/tags_users",
		"/v2/campus/:campus_id/tags_users",
		"/v2/tags/:tag_id/tags_users",
		"/v2/tags_users/:id",
	},
	"Teams": {
		"/v2/cursus/:cursus_id/teams/graph(/on/:field(/by/:interval))",
		"/v2/users/:user_id/teams/graph(/on/:field(/by/:interval))",
		"/v2/users/:user_id/projects/:project_id/teams/graph(/on/:field(/by/:interval))",
		"/v2/teams/graph(/on/:field(/by/:interval))",
		"/v2/projects/:project_id/teams/graph(/on/:field(/by/:interval))",
		"/v2/cursus/:cursus_id/teams",
		"/v2/users/:user_id/teams",
		"/v2/users/:user_id/projects/:project_id/teams",
		"/v2/teams",
		"/v2/projects/:project_id/teams",
		"/v2/project_sessions/:project_session_id/teams",
		"/v2/me/teams",
		"/v2/teams/:id",
		"/v2/teams/:id/reset_team_uploads",
	},
	"Teams uploads": {
		"/v2/teams/:team_id/teams_uploads",
		"/v2/teams_uploads",
		"/v2/teams_uploads/:id",
		"/v2/teams_uploads/multiple_create",
	},
	"Teams users": {
		"/v2/teams_users",
		"/v2/users/:user_id/teams_users",
		"/v2/teams/:team_id/teams_users",
		"/v2/teams_users/:id",
	},
	"Titles": {
		"/v2/titles",
		"/v2/users/:user_id/titles",
		"/v2/titles/:id",
	},
	"Titles users": {
		"/v2/titles/:title_id/titles_users",
		"/v2/users/:user_id/titles_users",
		"/v2/titles_users",
		"/v2/titles_users/:id",
	},
	"Transactions": {
		"/v2/transactions",
		"/v2/users/:user_id/transactions",
		"/v2/transactions/:id",
	},
	"Translations": {
		"/v2/translations",
		"/v2/translations/:id",
		"/v2/translations/upload",
	},
	"User candidatures": {
		"/v2/user_candidatures",
		"/v2/users/:user_id/user_candidature",
		"/v2/user_candidatures/:id",
	},
	"Users": {
		"/v2/users/graph(/on/:field(/by/:interval))",
		"/v2/users/:id/correction_points/add",
		"/v2/users/:id/correction_points/remove",
		"/v2/users/:id/locations_stats",
		"/v2/users/:id/exam",
		"/v2/coalitions/:coalition_id/users",
		"/v2/dashes/:dash_id/users",
		"/v2/events/:event_id/users",
		"/v2/accreditations/:accreditation_id/users",
		"/v2/teams/:team_id/users",
		"/v2/projects/:project_id/users",
		"/v2/partnerships/:partnership_id/users",
		"/v2/expertises/:expertise_id/users",
		"/v2/users",
		"/v2/cursus/:cursus_id/users",
		"/v2/campus/:campus_id/users",
		"/v2/achievements/:achievement_id/users",
		"/v2/titles/:title_id/users",
		"/v2/quests/:quest_id/users",
		"/v2/groups/:group_id/users",
		"/v2/users/:id",
		"/v2/me",
		"/v2/users/:user_id/free_past_agu",
		"/v2/users/:user_id/unfreeze",
		"/v2/staff",
	},
	"Waitlists": {
		"/v2/waitlists",
		"/v2/events/:event_id/waitlist",
		"/v2/exams/:exam_id/waitlist",
		"/v2/waitlists/:id",
	}
}